# Generated by Django 5.1.4 on 2025-01-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="images/team"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Determines order team members are displayed on the homepage. Use any numbers, locations will be ordered from smallest to largest.",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.DeleteModel(
            name="ActivityType",
        ),
        migrations.AlterModelOptions(
            name="gallerycategory",
            options={"verbose_name_plural": "gallery categories"},
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="display_on_homepage",
            field=models.BooleanField(
                default=True, help_text="Display on the home page"
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="caption_subtitle",
            field=models.CharField(
                blank=True,
                help_text="Optional caption subtitle, displayed on hover",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="caption_title",
            field=models.CharField(
                default="Sunshine Fitness",
                help_text="Caption title, displayed on hover",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="category",
            field=models.ForeignKey(
                help_text="Optional category, for filtering photos in the gallery section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.gallerycategory",
            ),
        ),
    ]
