# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='content',
            field=models.TextField(help_text='Note: single line breaks will be ignored when content isrendered on the site. Leave blank lines between paragraphs.'),
        ),
    ]
