# Generated by Django 5.1.4 on 2025-01-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_teammember_delete_activitytype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of reviewer", max_length=255),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name to display on the website", max_length=255
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="Optional occupation to display",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("review", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category, for filtering photos in the gallery section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.gallerycategory",
            ),
        ),
    ]
