# Generated by Django 5.1.4 on 2025-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_testimonial_alter_galleryimage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="facebook",
            field=models.URLField(
                blank=True, help_text="Optional facebook page link", null=True
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="instagram",
            field=models.URLField(
                blank=True, help_text="Optional instagram page link", null=True
            ),
        ),
    ]
