# Generated by Django 5.1.4 on 2025-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_teammember_facebook_teammember_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=models.TextField(help_text="Max 500 characters", max_length=500),
        ),
    ]
