# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20161003_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(help_text='File size must be less than 2Mb', upload_to='gallery'),
        ),
    ]
