# Generated by Django 3.2.8 on 2021-11-01 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disclaimercontent",
            options={"verbose_name": "Disclaimer Terms & PARQ"},
        ),
    ]
