# Generated by Django 3.0.3 on 2020-07-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dynamic_forms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.DecimalField(decimal_places=1, max_digits=100)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=255)),
                ('health_questionnaire_responses', dynamic_forms.models.ResponseField()),
                ('terms_accepted', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisclaimerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer_terms', models.TextField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=100, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('form', dynamic_forms.models.FormField(blank=True, null=True, verbose_name='health questionnaire')),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineDisclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.DecimalField(decimal_places=1, max_digits=100)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=255)),
                ('health_questionnaire_responses', dynamic_forms.models.ResponseField()),
                ('terms_accepted', models.BooleanField()),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_disclaimer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='onlinedisclaimer',
            index=models.Index(fields=['user'], name='accounts_on_user_id_03aad6_idx'),
        ),
    ]
