# Generated by Django 3.0.3 on 2020-07-30 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200724_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archiveddisclaimer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
