# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=22)),
                ('paid', models.BooleanField(default=False, help_text='Payment has been made by user')),
                ('date_booked', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_rebooked', models.DateTimeField(blank=True, null=True)),
                ('date_payment_confirmed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=255)),
                ('attended', models.BooleanField(default=False, help_text='Attended this event')),
                ('no_show', models.BooleanField(default=False, help_text='Paid but did not attend OR cancelled after allowed cancellation period')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop')], default='workshop', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(default='Carousel Fitness, 7 Preston Crescent, Inverkeithing, KY11 1DR', max_length=255)),
                ('max_participants', models.PositiveIntegerField(default=12)),
                ('contact_email', models.EmailField(default='carouselfitness@hotmail.com', max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('show_on_site', models.BooleanField(default=False, help_text='Display this event/workshop on the website')),
                ('cancellation_period', models.PositiveIntegerField(default=24)),
                ('email_studio_when_booked', models.BooleanField(default=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=['name', 'date'], unique=True)),
                ('allow_booking_cancellation', models.BooleanField(default=True)),
                ('paypal_email', models.EmailField(default='test-paypal@watermelon.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254)),
            ],
            options={
                'verbose_name': 'Workshop',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitinglistusers', to='booking.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitinglists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.Event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('user', 'event')]),
        ),
    ]
