# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglistuser',
            options={'verbose_name': 'waiting list', 'verbose_name_plural': 'waiting list'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_payment_confirmed',
        ),
        migrations.AlterField(
            model_name='event',
            name='paypal_email',
            field=models.EmailField(default='carouselfitness-test@gmail.com', help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]
