# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20160927_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(default='carouselfitness@gmail.com', max_length=254),
        ),
    ]
