# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20160927_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='Carousel Fitness, 7 Preston Crescent, Inverkeithing', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='show_on_site',
            field=models.BooleanField(default=False, help_text='Display this event/workshop on the website (if unticked, it will still be displayed for staff users for preview)'),
        ),
    ]
