# Generated by Django 4.0.6 on 2022-09-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='paypal_email',
        ),
    ]
