# Generated by Django 4.0.6 on 2022-09-28 07:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_payments", "0002_stripe_refund_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number_of_classes", models.PositiveIntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Visible and available for purchase on site",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="paypal_email",
        ),
        migrations.AddField(
            model_name="booking",
            name="checkout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="stripe_payments.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("workshop", "Workshop"),
                    ("regular_session", "Regular Timetabled Session"),
                    ("private", "Private Lesson"),
                ],
                default="regular_session",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "purchase_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        choices=[
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                            (2026, 2026),
                            (2027, 2027),
                            (2028, 2028),
                            (2029, 2029),
                            (2030, 2030),
                            (2031, 2031),
                            (2032, 2032),
                            (2033, 2033),
                            (2034, 2034),
                        ]
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="stripe_payments.invoice",
                    ),
                ),
                (
                    "membership_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="booking.membershiptype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="booking.membership",
            ),
        ),
    ]
