# Generated by Django 2.0.3 on 2019-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190119_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Workshop/Class', 'verbose_name_plural': 'Workshops/Classes'},
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_show',
            field=models.BooleanField(default=False, help_text='Booked but did not attend OR cancelled after allowed cancellation period'),
        ),
    ]
