# Generated by Django 2.0.3 on 2019-01-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_timetablesession_max_participants'),
        ('booking', '0006_auto_20190120_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Venue'),
        ),
    ]
