# Generated by Django 4.0.6 on 2022-09-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_membership_alter_event_event_type_usermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.usermembership'),
        ),
    ]
