# Generated by Django 4.0.6 on 2022-09-19 20:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0002_remove_invoice_business_email_and_more'),
        ('booking', '0006_membershiptype_booking_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount', models.PositiveIntegerField(blank=True, help_text='Discount value as a % of the purchased item cost. Enter a number between 1 and 100', null=True, verbose_name='Percentage discount')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount as an exact amount off the purchased item cost', max_digits=6, null=True, verbose_name='Exact amount discount')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('max_vouchers', models.PositiveIntegerField(blank=True, help_text='Maximum uses across all users', null=True, verbose_name='Maximum available vouchers')),
                ('max_per_user', models.PositiveIntegerField(blank=True, help_text='Maximum times this voucher can be used by a single user', null=True, verbose_name='Maximum uses per user')),
                ('is_gift_voucher', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, help_text='Name of recipient', max_length=255, null=True)),
                ('message', models.TextField(blank=True, help_text='Message (max 500 characters)', max_length=500, null=True)),
                ('purchaser_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='stripe_payments.invoice'),
        ),
        migrations.CreateModel(
            name='TotalVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.basevoucher')),
            ],
            bases=('booking.basevoucher',),
        ),
        migrations.CreateModel(
            name='ItemVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking.basevoucher')),
                ('event_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('workshop', 'Workshop'), ('regular_session', 'Regular Timetabled Session'), ('private', 'Private Lesson')], max_length=20), default=list, size=None)),
                ('membership_types', models.ManyToManyField(to='booking.membershiptype')),
            ],
            bases=('booking.basevoucher',),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.itemvoucher'),
        ),
        migrations.AddField(
            model_name='membership',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='booking.itemvoucher'),
        ),
    ]
