# Generated by Django 2.0.3 on 2019-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
