# Generated by Django 4.0.6 on 2022-09-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_stripe_pending_booking_user_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermembership',
            name='year',
            field=models.PositiveIntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034)], default=2022),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.usermembership'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('regular_session', 'Regular Timetabled Session'), ('private', 'Private Lesson')], default='regular_session', max_length=255),
        ),
    ]
