# Generated by Django 4.0.6 on 2022-09-20 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_basevoucher_alter_membership_invoice_totalvoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvoucher',
            name='event_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('workshop', 'Workshop'), ('regular_session', 'Regular Timetabled Session'), ('private', 'Private Lesson')], max_length=20), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='itemvoucher',
            name='membership_types',
            field=models.ManyToManyField(blank=True, to='booking.membershiptype'),
        ),
    ]
