# Generated by Django 4.1.1 on 2022-09-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_giftvouchertype_giftvoucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cancellation_period",
            field=models.PositiveIntegerField(default=12),
        ),
    ]
