# Generated by Django 2.0.3 on 2019-01-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularClass',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('booking.event',),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('booking.event',),
        ),
    ]
