# Generated by Django 4.0.6 on 2022-09-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_itemvoucher_event_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
