# Generated by Django 4.1.1 on 2023-03-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_event_cancellation_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cancellation_period",
            field=models.PositiveIntegerField(default=24),
        ),
    ]
