# Generated by Django 4.0.6 on 2022-09-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_usermembership_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.usermembership'),
        ),
    ]
