# Generated by Django 4.0.6 on 2022-09-22 20:52

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_membershiptype_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevoucher',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount as an exact amount off the purchased item cost', max_digits=6, null=True, verbose_name='Exact discount amount (£)'),
        ),
        migrations.AlterField(
            model_name='basevoucher',
            name='start_date',
            field=models.DateTimeField(default=booking.models._start_of_today),
        ),
    ]
