# Generated by Django 2.0.3 on 2019-01-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_regularclass_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('booking.event',),
        ),
    ]
