# Generated by Django 2.0.3 on 2019-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularclass',
            options={'verbose_name_plural': 'regular classes'},
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
