# Generated by Django 4.0.6 on 2022-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_basevoucher_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_pending',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
