# Generated by Django 4.0.6 on 2022-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_stripe_pending_booking_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='active',
            field=models.BooleanField(default=True, help_text='Visible and available for purchase on site'),
        ),
    ]
