# Generated by Django 3.0.3 on 2020-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190123_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email_studio_when_booked',
            field=models.BooleanField(default=False),
        ),
    ]
