# Generated by Django 3.0.3 on 2020-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20200228_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee_incurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
