# Generated by Django 4.0.6 on 2022-09-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0004_striperefund_booking_id_and_more'),
        ('booking', '0012_membershiptype_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVoucherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('regular_session', 'Regular Timetabled Session'), ('private', 'Private Lesson')], max_length=255, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Exact amount discount (£)')),
                ('active', models.BooleanField(default=True, help_text='Display on site; set to False instead of deleting unused gift voucher types')),
                ('duration', models.PositiveIntegerField(default=6, help_text='How many months will this gift voucher last?')),
                ('membership_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher_types', to='booking.membershiptype')),
            ],
            options={
                'ordering': ('event_type', 'membership_type', 'discount_amount'),
                'unique_together': {('event_type', 'membership_type', 'discount_amount')},
            },
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
                ('gift_voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.giftvouchertype')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='stripe_payments.invoice')),
                ('item_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='booking.itemvoucher')),
                ('total_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_vouchers', to='booking.totalvoucher')),
            ],
        ),
    ]
