# Generated by Django 4.0.6 on 2022-09-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_giftvouchertype_giftvoucher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='giftvouchertype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='giftvouchertype',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, unique=True, verbose_name='Exact amount discount (£)'),
        ),
        migrations.AlterField(
            model_name='giftvouchertype',
            name='event_type',
            field=models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('regular_session', 'Regular Timetabled Session'), ('private', 'Private Lesson')], max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='giftvouchertype',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher_types', to='booking.membershiptype', unique=True),
        ),
    ]
