# Generated by Django 3.0.3 on 2020-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_add_default_cancellation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
