# Generated by Django 4.0.6 on 2022-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_giftvouchertype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvouchertype',
            name='override_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Use this to override the default cost to purchase this gift voucher. (Default cost is the current cost of the item the voucher is for (i.e. the discount amount, or for memberships, the current cost to purchase that membership, and for classes/privates/workshops, the cost of the last event of that type that was created.', max_digits=8, null=True),
        ),
    ]
