# Generated by Django 4.0.6 on 2022-09-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_giftvouchertype_override_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvouchertype',
            name='membership_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher_types', to='booking.membershiptype'),
        ),
    ]
