# Generated by Django 3.0.3 on 2020-03-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_date_cancelled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
