# Generated by Django 3.0.3 on 2020-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_delete_register'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'event_type'], name='booking_eve_date_8f664b_idx'),
        ),
    ]
