# Generated by Django 4.0.6 on 2022-09-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_giftvouchertype_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='item_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher', to='booking.itemvoucher'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='total_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_voucher', to='booking.totalvoucher'),
        ),
    ]
