# Generated by Django 3.0.3 on 2020-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20200303_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Classes are only available to students with memberships'),
        ),
    ]
