# Generated by Django 3.0.3 on 2021-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_event_members_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paypal_email',
            field=models.EmailField(help_text='Email for the paypal account to be used for payment.  Check this carefully!', max_length=254),
        ),
    ]
