---
- name: Setup Virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ project_root_path }}/requirements.txt virtualenv_python=python3.4

- name: Install some dev tools
  sudo: yes
  pip: name={{ item }} virtualenv={{ virtualenv_path }}
  with_items:
    - ipdb
    - ipython
    - django-extensions

- name: Django db
  django_manage: command={{ item }} app_path={{ project_root_path }} virtualenv={{ virtualenv_path }}
  with_items:
    - migrate

