---
- name: Remove Upstart script for uWSGI
  file: path=/etc/init/uwsgi.conf state=absent

- name: Install uWSGI
  apt: name={{item}}
  with_items:
    - uwsgi
    - uwsgi-plugin-python
    - uwsgi-plugin-python3
