#!/bin/bash

virtualenv venv
source venv/bin/activate && (
    pip install -r requirements.txt
    ./utils/make_secret_key
    envdir envdir ./manage.py collectstatic
    envdir envdir ./manage.py syncdb
    service nginx restart
    service uwsgi restart
)
