#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import mkdir
from os.path import join, dirname, exists
import random
import sys

HERE = dirname(__file__)

chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890!@#$%^&*()/=?+-_'


def generate_secret_key():
    return ''.join(random.choice(chars) for _ in range(24))


def main(argv=sys.argv[1:]):
    envdir = join(HERE, '../envdir')
    path = join(envdir, 'SECRET_KEY')

    if not exists(envdir):
        mkdir(envdir)

    if exists(path):
        print 'File already exists. Exiting.'
    else:
        with open(path, 'w') as fh:
            fh.write(generate_secret_key())
        print 'Done'


if __name__ == '__main__':
    main()
