from django.conf.urls import patterns, url

urlpatterns = patterns(
    'polefit.website.views',
    url(r'^$',                  'index', name='index'),
    url(r'^about$',             'about', name='about'),
    url(r'^(?P<session_type_id>\d+)/classes/$', 'classes', name='classes'),
    url(r'^(?P<instructor_id>\d+)/instructor/$', 'instructor_info', name='instructor_info'),
    url(r'^instructors$',       'instructors', name='instructors'),
    url(r'^events$',       'events', name='events'),
    url(r'^venues$',            'venues', name='venues'),
    url(r'^booking$',           'booking', name='booking'),
    url(r'^parties$',           'parties', name='parties'),
    url(r'^gallery$',           'gallery', name='gallery'),
    url(r'^(?P<category_id>\d+)/gallery/category/$', 'gallery_category', name='gallery_category'),
    url(r'^timetable$',           'timetable', name='timetable'),
    url(r'^(?P<session_type_id>\d+)/classes/sessions/$', 'sessions_by_type', name='sessions_by_type'),
    url(r'^this_week$',     'weekly_table', {'week':'this', 'venue_id': 'all'}, name='this_week_table'),
    url(r'^this_week/(?P<venue_id>\d+)/$',     'weekly_table', {'week':'this'}, name='this_week_table_venue'),
    url(r'^next_week$',     'weekly_table', {'week':'next', 'venue_id': 'all'}, name='next_week_table'),
    url(r'^next_week/(?P<venue_id>\d+)/$',     'weekly_table', {'week':'next'}, name='next_week_table_venue'),
    url(r'^polefit_admin_help/help$',           'admin_help_login', name='admin_help_login'),
    url(r'^polefit_admin_help/help/sessions$',           'admin_help_sessions', name='admin_help_sessions'),
    url(r'^polefit_admin_help/help/sessiontypes$',           'admin_help_sessiontypes', name='admin_help_sessiontypes'),
    url(r'^polefit_admin_help/help/instructors$',           'admin_help_instructors', name='admin_help_instructors'),
    url(r'^polefit_admin_help/help/venues$',           'admin_help_venues', name='admin_help_venues'),
    url(r'^polefit_admin_help/help/gallery$',           'admin_help_gallery', name='admin_help_gallery'),
    url(r'^polefit_admin_help/help/about',           'admin_help_about', name='admin_help_about'),
    url(r'^polefit_admin_help/help/events',           'admin_help_events', name='admin_help_events'),
)
