# Generated by Django 4.0.6 on 2022-09-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transaction_id',
        ),
    ]
