# Generated by Django 4.0.6 on 2022-09-22 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0002_remove_invoice_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Purchaser email'),
        ),
        migrations.CreateModel(
            name='StripeRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('metadata', models.JSONField()),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='stripe_payments.invoice')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='stripe_payments.stripepaymentintent')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripe_payments.seller')),
            ],
        ),
    ]
