# Generated by Django 4.0.6 on 2022-09-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0003_alter_invoice_username_striperefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='striperefund',
            name='booking_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripepaymentintent',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='stripe_payments.invoice'),
        ),
    ]
