# Generated by Django 3.2.8 on 2021-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipcategory",
            name="colour",
            field=models.CharField(
                choices=[
                    ("primary", "blue"),
                    ("danger", "red"),
                    ("warning", "yellow"),
                    ("success", "green"),
                    ("info", "light blue"),
                ],
                default="primary",
                help_text="For colour-coding classes on timetable",
                max_length=20,
            ),
        ),
    ]
