# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20151115_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
