# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20160927_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='membership_category',
            field=models.CharField(blank=True, choices=[(1, 'Pole and hoop classes'), (2, 'General fitness and conditioning classes'), (3, 'Open training')], help_text='Specify type of class for membership purposes', max_length=1, null=True),
        ),
    ]
