# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:42
from __future__ import unicode_literals

from django.db import migrations


def add_membership_category(apps, schema_editor):
    TimetableSession = apps.get_model("timetable", "TimetableSession")

    for ttsession in TimetableSession.objects.all():
        if ttsession.membership_level:
            ttsession.membership_category = ttsession.membership_level.membership_level
            ttsession.save()


def remove_membership_category(apps, schema_editor):
    TimetableSession = apps.get_model("timetable", "TimetableSession")
    MembershipClassLevel = apps.get_model("timetable", "MembershipClassLevel")

    for ttsession in TimetableSession.objects.all():
        if ttsession.membership_category:
            mem_level, _ = MembershipClassLevel.objects.get_or_create(
                membership_level=ttsession.membership_category
            )
            ttsession.membership_level = mem_level
            ttsession.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_timetablesession_membership_category'),
    ]

    operations = [
        migrations.RunPython(
            add_membership_category, remove_membership_category
        ),
    ]
