# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_data_migration_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablesession',
            name='membership_level',
        ),
        migrations.DeleteModel(
            name='MembershipClassLevel',
        ),
    ]
