# Generated by Django 5.1.4 on 2024-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timetablesession_cancellation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(default='tbc', help_text='Name for this location. Timetables will be grouped by location.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='abbreviation',
            field=models.CharField(default='', help_text='Short name for this venue. This will appear on the timetables.', max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(default='Venue TBC', help_text='Full name for this venue. This will appear on the Venues page.', max_length=255),
        ),
    ]
