# Generated by Django 5.1.4 on 2025-01-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0008_timetablesession_cancellation_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this location. Timetables will be grouped by location. Multiple venues can share the same location and will be displayed on the same timetable.",
                        max_length=255,
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=255, null=True)),
                ("postcode", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="sessiontype",
            options={
                "ordering": ("order", "id"),
                "verbose_name": "session type",
                "verbose_name_plural": "session types",
            },
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ("order", "location")},
        ),
        migrations.RenameField(
            model_name="sessiontype",
            old_name="info",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="sessiontype",
            name="index",
        ),
        migrations.RemoveField(
            model_name="sessiontype",
            name="regular_session",
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="display_on_site",
            field=models.BooleanField(
                default=True,
                help_text="Include this activity type and its description on the 'what we offer' page",
                verbose_name="display on site",
            ),
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="order",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Determines order activities are displayed on the 'what we offer' page. Use any numbers, locations will be ordered from smallest to largest.",
            ),
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/activity_types"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="display_on_site",
            field=models.BooleanField(
                default=True, help_text="Display this venue on the Venues page"
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="order",
            field=models.IntegerField(
                default=100,
                help_text="For ordering of venues (on Venues page on website) and location tabs on timetables; use any numbers, venues/locations will be ordered from smallest to largest.",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/venue"),
        ),
        migrations.AlterField(
            model_name="timetablesession",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign a category if you want to colour-code sessions on the timetable (e.g. to group by class cost, membership etc)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.category",
            ),
        ),
        migrations.AlterField(
            model_name="timetablesession",
            name="session_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="timetable.sessiontype"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="abbreviation",
            field=models.CharField(
                default="",
                help_text="Short name for this venue. This will appear on the timetables.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(
                default="Venue TBC",
                help_text="Full name for this venue. This will appear on the Venues page.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="location",
            field=models.ForeignKey(
                help_text="Location (address) of this venue. Timetables will be grouped by location. Multiple venues can share the same location and will be displayed on the same timetable.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.location",
            ),
        ),
    ]
