# Generated by Django 5.1.4 on 2024-12-28 10:46

from django.db import migrations


def add_default_location(apps, schema_editor):
    Venue = apps.get_model("timetable", "Venue")
    Location = apps.get_model("timetable", "Location")

    for venue in Venue.objects.all():
        if venue.postcode:
            location_name = venue.postcode
        else:
            location_name = venue.name

        location, _ = Location.objects.get_or_create(
            name=location_name, postcode=venue.postcode, address=venue.address
        )
        venue.location = location
        venue.save()


def revert_location(apps, schema_editor):
    Venue = apps.get_model("timetable", "Venue")

    for venue in Venue.objects.all():
        venue.address = venue.location.address
        venue.postcode = venue.location.postcode
        venue.save()


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0009_location_alter_sessiontype_options_and_more"),
    ]

    operations = [
        migrations.RunPython(add_default_location, reverse_code=revert_location)
    ]
