# Generated by Django 5.1.4 on 2024-12-28 10:46

from django.db import migrations


def add_default_location(apps, schema_editor):
    Venue = apps.get_model('timetable', 'Venue')

    for venue in Venue.objects.all():
        if venue.postcode:
            venue.location = venue.postcode
        else:
            venue.location = venue.name
        venue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_venue_location_alter_venue_abbreviation'),
    ]

    operations = [
        migrations.RunPython(
            add_default_location, reverse_code=migrations.RunPython.noop
        )
    ]
