# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20161004_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Please upload a .jpg image with equal height and width. File size must be less than 2Mb.', null=True, upload_to='instructors'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='photo',
            field=models.ImageField(blank=True, help_text='File size must be less than 2Mb', null=True, upload_to='sessions'),
        ),
    ]
