# Generated by Django 5.1.4 on 2024-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_add_default_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('tab_order', 'location')},
        ),
        migrations.AddField(
            model_name='venue',
            name='tab_order',
            field=models.IntegerField(default=100, help_text='For ordering of location tabs; use any numbers, locations will be ordered from smallest to largest.'),
        ),
    ]
