# Generated by Django 5.1.4 on 2025-01-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_add_default_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='postcode',
        ),
    ]
