# Generated by Django 2.0.3 on 2019-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20161004_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='max_participants',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
