# Generated by Django 5.1.4 on 2025-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_alter_venue_options_venue_tab_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'verbose_name': 'session type', 'verbose_name_plural': 'session types'},
        ),
        migrations.RenameField(
            model_name='sessiontype',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sessiontype',
            old_name='regular_session',
            new_name='display_on_site'
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/activity_types'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='index',
            field=models.PositiveIntegerField(blank=True, help_text="Determines order activities are displayed on the 'what we offer' page", null=True),
        ),
    ]
