# Generated by Django 5.1.4 on 2025-01-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_alter_sessiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='display_on_site',
            field=models.BooleanField(default=True, help_text="Include this activity type and its description on the 'what we offer' page", verbose_name='display on site'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/activity_types'),
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Assign a category if you want to colour-code sessions on the timetable (e.g. to group by class cost, membership etc)', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.category'),
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.sessiontype'),
        ),
    ]
