# Generated by Django 3.0.3 on 2020-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20191020_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
