# Generated by Django 5.1.4 on 2025-01-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_alter_sessiontype_display_on_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='display_on_site',
            field=models.BooleanField(default=True, help_text='Display this venue on the Venues page'),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/venue'),
        ),
    ]
