# Generated by Django 3.0.3 on 2020-02-28 23:43

from django.db import migrations


def default_cancellation_fees(apps, schema_editor):
    Event = apps.get_model('booking', 'Event')
    for event in Event.objects.all():
        event.cancellation_fee = 1.0
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20200228_2014'),
    ]

    operations = [
        migrations.RunPython(default_cancellation_fees),
    ]
