# Generated by Django 5.1.4 on 2025-01-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_venue_description_venue_display_on_site_venue_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'ordering': ('order', 'id'), 'verbose_name': 'session type', 'verbose_name_plural': 'session types'},
        ),
        migrations.RenameField(
            model_name='sessiontype',
            old_name='index',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.CharField(help_text='Name for this location. Timetables will be grouped by location. Multiple venues can share the same location and will be displayed on the same timetable.', max_length=255),
        ),
    ]
