# Generated by Django 3.0.3 on 2020-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_add_default_cancellation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='members_only',
            field=models.BooleanField(default=False, help_text='Classes are only available to students with memberships'),
        ),
    ]
