# Generated by Django 3.0.3 on 2020-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_timetablesession_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesession',
            name='show_on_timetable_page',
            field=models.BooleanField(default=True, help_text='Display this session on the website timetable page'),
        ),
    ]
