# Generated by Django 5.1.4 on 2025-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_alter_sessiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text="Determines order activities are displayed on the 'what we offer' page. Use any numbers, locations will be ordered from smallest to largest."),
        ),
    ]
