# Generated by Django 5.1.4 on 2025-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_alter_sessiontype_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
