---
- hosts: all
  sudo: true
  gather_facts: no

  vars_files:
  - vault.yml

  roles:
  - common
  - nginx
  - uwsgi
  - postgresql
  - {
      role: djangoapp,
      site: polefit,
      server_name: ".polefitstarlet.co.uk",
      app_root: "/opt/sites/{{site}}",
      dbpassword: "{{ polefit_db_password }}",
      secret_key: "{{ polefit_secret_key }}",
      repo: 'git@bitbucket.org:markandbecky/polefit.git',
  }
  - {
      role: djangoapp,
      site: pipsevents,
      server_name: ".pipsevents.co.uk booking.thewatermelonstudio.co.uk",
      app_root: "/opt/sites/{{site}}",
      dbpassword: "{{ pipsevents_db_password }}",
      secret_key: "{{ pipsevents_secret_key }}",
      repo: "git@github.com:rebkwok/pipsevents.git",
      uwsgi_plugin: "python3",
      python: "/usr/bin/python3",
  }
