---
- hosts: all
  sudo: true
  gather_facts: no

  vars:
    site: polefit
    app_root: /opt/sites/{{site}}
    dbpassword: mysupersecretpassword

  roles:
    #- common
    #- nginx
    #- uwsgi
    #- postgresql
    - djangoapp

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no


