---
- hosts: all
  sudo: true
  gather_facts: no

  vars_files:
  - vault.yml

  pre_tasks:
  - name: Install deployment key
    copy: src=../{{item}} dest=/root/.ssh/{{item}} mode=0600
    with_items:
    - id_rsa
    - id_rsa.pub

  roles:
  - common
  - nginx
  - uwsgi
  - postgresql
  - {
      role: djangoapp,
      site: polefit,
      app_root: "/opt/sites/{{site}}",
      dbpassword: "{{ polefit_db_password }}",
      secret_key: "{{ polefit_secret_key }}",
      repo: 'git@bitbucket.org:markandbecky/polefit.git',
  }
  - {
      role: djangoapp,
      site: pipsevents,
      app_root: "/opt/sites/{{site}}",
      dbpassword: "{{ pipsevents_db_password }}",
      secret_key: "{{ pipsevents_secret_key }}",
      repo: "https://github.com/rebkwok/pipsevents.git",
  }

